name: Build and Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for release (for logging only)'
        required: false
        type: string

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build twine

      - name: Build package
        run: |
          python -m build

      - name: List build files
        run: |
          ls -lh dist

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version || github.run_id }}
          name: Release ${{ github.event.inputs.version || github.run_id }}
          files: |
            dist/*.tar.gz
            dist/*.whl
